### ISSUE TITLE
calibration target

### ISSUE THREAD

**Issue by hanhanhan-kim** [lambdaloop/anipose#32]
Hello!

I have a quick question not regarding the code base, so I apologize if the GitHub issues section is an inappropriate place for me to ask--but I thought a lot of people might find this question relevant, and there seems to be a lot of traction here.

I noticed in your wonderful and detailed preprint that the ChArUco board was manufactured by Applied Image Inc to a very precise level. I was wondering if you guys had any luck with a homemade ChArUco target--e.g. something you might print out and then tape to a little piece of acrylic. Or was purchasing a custom manufactured board necessary? 

Back when I was playing around with Anipose (5 months ago now ...) I noticed I was getting pretty good 2D labels from DeepLabCut, but my 3D model looked absolutely horrendous. I suspected it likely had to do with poor triangulation, which might ultimately have been caused by a less than ideal calibration target? My calibration target was relatively janky--I printed it on a sheet of paper and taped it flat to a small piece of acrylic. I then manually waved it about in front of my cameras. My use case is similar, in scale, to yours--the movements of very tiny insects (not flies though). 

Do you think such scales necessitate precision-manufactured ChArUco boards?

Thanks!

**Comment by lambdaloop** [comment]
I think it depends on your scale.

About a year ago, I performed some tests with our printers to see if I could get good printing of small targets.
You can see the results here:
https://docs.google.com/presentation/d/1mFdfadmKGhGPCUQ0QYYTBaMWqk9X39vFfzNWNfxacr4/edit?usp=sharing

This was done with a 1200 dpi laser printer and comparable inkjet printer. 
I tried different sizes of calibration boards and types of papers. 
I couldn't get precise enough patterns at the scale that I needed, however (< 4 mm).  That's why we ended up going with Applied Image Inc to make a precise charuco board.  

If you a calibration board above 4mm is okay, then I think you could make one with a printer! Based on my experiments, I highly recommend using a laser printer with the print quality set to 1200 dpi (or above if possible) and black and white. The type of paper doesn't matter too much.

**Comment by hanhanhan-kim** [comment]
Thank you very much! I really appreciate your detailed response :)
