### ISSUE TITLE
Documentation Errors

### ISSUE THREAD

**Issue by jinu-jang** [lambdaloop/anipose#4]
While I was trying to use anipose for 3D calibration purposes, I came across a couple things in the current documentation that could be changed to prevent confusion for future users.

- In `start_3d.md`, under the [https://github.com/lambdaloop/anipose/blob/master/docs/start_3d.md#drawing-the-calibration-board(url),
    `anipose draw_calibration` is actually `anipose draw-calibration`

- Also if we're doing 3D projects, turns out because the minimum number of folders are 2 (calibration and videos-raw), I had to set `nesting=2` in the `config.toml` file or none of the code even executes.

- If the GPU is being used by something else, like a Jupyter Notebook environment which was idling with DeepLabCut, it threw the following error and stopped me from using anipose.

> 019-10-29 20:57:14.464694: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2019-10-29 20:57:14.467602: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\dlc_gpu\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "c:\programdata\anaconda3\envs\dlc_gpu\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "c:\programdata\anaconda3\envs\dlc_gpu\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node resnet_v1_50/conv1/Conv2D}}]]
         [[{{node concat_1}}]]

Thank you for your work!

**Comment by lambdaloop** [comment]
Hello @jimjang95,

Thank you for this issue! 

For draw-calibration vs draw_calibration, I'm not sure why but different operating systems it only allows one of the two... I will either change anipose to allow both and clarify this in the documentation.

Regarding nesting, the nesting variable specifies the depth of the directory structure, rather than how many folders are present. I will edit the documentation to clarify this as well.

For the GPU, yes, that is indeed a general issue with DeepLabCut. This should only affect `anipose analyze`, as no other step uses the GPU. I will make a note of this in the documentation as well.

I will do an overhaul of the documentation within the next month and will make the edits then.

**Comment by johnmbarrett** [comment]
Another issue I've noticed with the documentation is that, on readthedocs.io, certain code blocks (mostly pertaining to example configs) aren't rendered, at least in Firefox 77.0 under Windows 10. See the below screenshot: on the left is setup3d.html on readthedocs.io, right is setup3d.rst rendered on GitHub. The example configs for triangulation and angles are missing on readthedocs.io.

![anipose_doc_error](https://user-images.githubusercontent.com/19190699/84198596-61f5ad00-aa69-11ea-84dc-dcc9355eb146.png)

**Comment by lambdaloop** [comment]
I think all of these issues have been resolved now
