### ISSUE TITLE
[ENH] ffmpeg + opencv wrapper image processing scripts

### ISSUE THREAD

**Issue by alexrockhill** [lambdaloop/anipose#47]
I made some image processing scripts to take a raw video with claps in it and synchronize several cameras based on the audio. I'm not sure if there is a better way to do it, but the documentation starts at three synchronized videos so I thought those might be useful to getting unedited video into the anipose format.

Also is anyone maintaining this repository? @lambdaloop @katierupp @tuthill-lab

**Comment by lambdaloop** [comment]
Hello, I'm maintaining the repository. It can take me longer to respond sometimes though... 

I have some scripts that do something similar as well, that's how we synchronized the hand videos. It's interesting to see other people have the issue!

Are you interesting in contributing your code? It would be cool to add a function to Anipose that does this, so that you can start from unsynced videos and process the whole pipeline automatically.

Alternatively, what do you think the best course of action should be for such code?

**Comment by alexrockhill** [comment]
Hey @lambdaloop, sorry to bother about maintaining the repository, I just wanted to check before putting effort into making PRs to make sure there weren't going to be no responses, slow responses are just fine.

I thought it could be helpful to others so I could definitely make a PR. I found that using OpenCV alone was preferable to video cropping with ffmpeg because ffmpeg can crop the videos weirdly to try and sync with the sound of a video (the millisecond precision is lost; see here for instance https://superuser.com/questions/1154799/ffmpeg-extremely-precise-extraction-of-video-segments). I'm taking the ffmpeg dependencies and streamlining a bit and then I should have it ready for a PR later this week.

**Comment by lambdaloop** [comment]
Oh interesting, I didn't realize that ffmpeg had this issue. Sounds good! Anipose already interacts with ffmpeg using scikit-video, if it helps at all. 

Looking forward to your PR!

**Comment by lambdaloop** [comment]
Oh interesting, I didn't realize that ffmpeg had this issue. Sounds good! Anipose already interacts with ffmpeg using scikit-video, if it helps at all. 

Looking forward to your PR!

**Comment by lambdaloop** [comment]
I feel like this is an older issue now. I'll close this and leave the PR open so discussion can happen there
