### ISSUE TITLE
Notebook not finding cv2

### ISSUE THREAD

**Issue by roaldarbol** [lambdaloop/anipose#53]
Hi guys,
I'm just testing out anipose, but on a machine without GPU support (so analysis would take forever). So I decided to try the notebook on Google Colab to make use of their GPU acceleration; I've added a few lines in the top, uninstalling opencv-python and installing aniposelib (and for good measure making sure that the opecv-contrib-python is indeed installed), but would think it possible to continue from there.

But I am for some reason getting an error stating that cv2 cannot be found. 

Entire error message here:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-3657c5a7600f> in <module>()
      1 import numpy as np
----> 2 from aniposelib.boards import CharucoBoard, Checkerboard
      3 from aniposelib.cameras import Camera, CameraGroup
      4 from aniposelib.utils import load_pose2d_fnames

3 frames
/usr/lib/python3.6/imp.py in find_module(name, path)
    295         break  # Break out of outer loop when breaking out of inner loop.
    296     else:
--> 297         raise ImportError(_ERR_MSG.format(name), name=name)
    298 
    299     encoding = None

ImportError: No module named 'cv2'
```

I did also notice that the notebook uses Python3.6, but in the docs the conda environment uses 3.7. I don't know if that's valuable, but might be worth checking up.

Thanks for all your work on making anipose, I look very much forward to trying it out in the wild!

**Comment by lambdaloop** [comment]
Do you have a link to the Colab notebook (or perhaps a smaller version that reproduces the problem) ? 
It sounds like it's some kind of environment issue, but I'm not sure how to debug this without more information

**Comment by roaldarbol** [comment]
I never figured out what the error really was, but next time I tried, it worked. I had modified the Colab notebook which resides in the [Google Drive](https://drive.google.com/drive/u/0/folders/1Y4qzeL80mXOvDAJpbAsnQQLXeoBcvtK0), to install anipose from pip. 
Have since gotten a new laptop and haven't had issues since. So I assume you're right it must have been an environment issue.

**Comment by Virginia9733** [comment]
> I never figured out what the error really was, but next time I tried, it worked. I had modified the Colab notebook which resides in the [Google Drive](https://drive.google.com/drive/u/0/folders/1Y4qzeL80mXOvDAJpbAsnQQLXeoBcvtK0), to install anipose from pip.
> Have since gotten a new laptop and haven't had issues since. So I assume you're right it must have been an environment issue.

Hi,
I am trying to use anipose on colab as well since I don't have a laptop with GPU.
However, following the installation instruction, I could not install wxPython on colab, under the conda env that required.

I checked your notebook and haven't find the codes that how you successfully install anipose on colab.

When I try this code in the cell:

%%shell
eval "$(conda shell.bash hook)" # copy conda command to shell
conda activate anipose_env

python -m pip install -U \
    -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 \
    wxPython

I got this error message:
Looking in links: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04
Collecting wxPython
  Using cached wxPython-4.1.1.tar.gz (66.0 MB)
Requirement already satisfied: pillow in /usr/local/envs/anipose_env/lib/python3.7/site-packages (from wxPython) (8.2.0)
Requirement already satisfied: six in /usr/local/envs/anipose_env/lib/python3.7/site-packages (from wxPython) (1.15.0)
Requirement already satisfied: numpy in /usr/local/envs/anipose_env/lib/python3.7/site-packages (from wxPython) (1.17.5)
Building wheels for collected packages: wxPython
  Building wheel for wxPython (setup.py) ... error
  ERROR: Failed building wheel for wxPython
  Running setup.py clean for wxPython
Failed to build wxPython
Installing collected packages: wxPython
    Running setup.py install for wxPython ... error
ERROR: Command errored out with exit status 1: /usr/local/envs/anipose_env/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bve7chve/wxpython_0bded69748294a3ab1cc8b713561d14a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bve7chve/wxpython_0bded69748294a3ab1cc8b713561d14a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x4tzej7u/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/envs/anipose_env/include/python3.7m/wxPython Check the logs for full command output.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-31-a492919fc844> in <module>()
      1 
----> 2 get_ipython().run_cell_magic('shell', '', 'eval "$(conda shell.bash hook)" # copy conda command to shell\nconda activate anipose_env\n\npython -m pip install -U \\\n    -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 \\\n    wxPython')

2 frames
/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py in check_returncode(self)
    137     if self.returncode:
    138       raise subprocess.CalledProcessError(
--> 139           returncode=self.returncode, cmd=self.args, output=self.output)
    140 
    141   def _repr_pretty_(self, p, cycle):  # pylint:disable=unused-argument

CalledProcessError: Command 'eval "$(conda shell.bash hook)" # copy conda command to shell
conda activate anipose_env

python -m pip install -U \
    -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 \
    wxPython' returned non-zero exit status 1.

**Comment by roaldarbol** [comment]
I've made it work without running conda in Google Colab (which seems like a lot of work to get to work), just by adding this to the top of the .ipynb:
```
!pip install aniposelib
```
```
#Now, let's link to your GoogleDrive. Run this cell and follow the authorization instructions:
#(If you're running this with the provided example, make sure that it's in your Google Drive)

from google.colab import drive
drive.mount('/content/drive')
```
```
# Change directory to the correct folder with the videos (may not be the same as this one)
%cd /content/drive/MyDrive/anipose/2020-04-02-aniposelib-hand-demo/   
```

**Comment by Virginia9733** [comment]
Thank you so much!!!! 
However, I tried to install anipose directly in colab, but get this error message:
![Screen Shot 2021-06-03 at 7 07 49 PM](https://user-images.githubusercontent.com/61534754/120635437-0ce35000-c49f-11eb-9b6c-e2e4d14d69da.png)

Then I redirect the working directory to the demo folder and tried to run anipose analyze
I got this error message...
![Screen Shot 2021-06-03 at 7 07 59 PM](https://user-images.githubusercontent.com/61534754/120635488-1c629900-c49f-11eb-83f1-3fe00c4ca8cc.png)

**Comment by Virginia9733** [comment]
However, when I run anipose in conda, it could import anipose, but failed when I run anipose analyze
No module named wx.
![Screen Shot 2021-06-03 at 7 14 23 PM](https://user-images.githubusercontent.com/61534754/120636273-06090d00-c4a0-11eb-90e8-990d4e0cbcdb.png)

**Comment by roaldarbol** [comment]
It seems you're trying to call terminal/command prompt commands (e.g. 'anipose analyze'), which won't work (without, again, quite a bit of other adaptations). Just use the python notebook available within their Google Drive ([direct link ](https://colab.research.google.com/drive/1dvz4laB6q0uXgIXDK-6siwLZDIuF4bro)to the file), and insert the lines I mentioned.  Then it should work. :-)

**Comment by Virginia9733** [comment]
Thank you very much!!! I could install aniposelib in colab, however, since the code in their tutorial is all in the terminal, I am quite lost about which functions should I call to analyze the video, like analyze, filter, etc. 
https://anipose.readthedocs.io/en/latest/tutorial.html 
I am sorry :-(
