### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable during calibration

### ISSUE THREAD

**Issue by aaroncherian** [lambdaloop/anipose#70]
Hi,

I was sending some videos through the anipose pipeline, and I was running into this error : 'TypeError: 'NoneType' object is not subscriptable during calibration', specifically at this point in the code: 
```
for new in graph[item]:
            if new not in explored:
                q.append(new)
                pairs.append( (item, new) )
```
with the line 'for new in graph[item]. I've seen that this problem has popped up before for others, so I tried to do a bit of digging into why 'graph' was coming up as None and causing this error.

I did a bit of digging and found this section (in utils.py):

```
def get_calibration_graph(rtvecs, cam_names=None):
    n_cams = rtvecs.shape[0]
    n_points = rtvecs.shape[1]

    if cam_names is None:
        cam_names = np.arange(n_cams)

    connections = get_connections(rtvecs, cam_names)

    components = dict(zip(cam_names, range(n_cams)))
    edges = set(connections.items())

    # print(sorted(edges))

    graph = defaultdict(list)

    for edgenum in range(n_cams-1):
        if len(edges) == 0:
            return None

        (a, b), weight = max(edges, key=lambda x: x[1])
        graph[a].append(b)
        graph[b].append(a)

        match = components[a]
        replace = components[b]
        for k, v in components.items():
            if match == v:
                components[k] = replace

        for e in edges.copy():
            (a,b), w = e
            if components[a] == components[b]:
                edges.remove(e)

    return graph
```
Here's my attempt at interpreting what's going on, apologies if I've misread something here. This is the function that creates that 'graph' variable. Within this function, it seems that 'edges' is created by the function get_connections, which incorporates the rtvecs. 

Then we have this for loop running  for each of the cameras, where at the end of an iteration of the loop, it removes a number from the list in 'edges'. 

So what seems to be happening with these videos is that at some point during this process, for some reason, 'edges' gets emptied out, which triggers the 'if len(edges) == 0' statement, which then returns graph as None, causing the NoneType error. 

That being said, I'm not sure what exactly, in a larger sense, variables like 'edges' or functions like 'get_connections( )' mean, so I'm having trouble parsing through what exactly happens when these videos are fed through that affects the 'edges' variable, and causes this NoneType error, and how to deal with it. Thanks!

Here's a link to the videos I was running through Anipose: https://www.dropbox.com/sh/u54fnrhe3wbbbeh/AADsFmbMjrk_QBJnVuVHy2dla?dl=0

**Comment by lambdaloop** [comment]
Hello, I realize this is quite late but I finally had some time to look into this more deeply. 

I was able to reproduce the issue. There are actually multiple issues. 

First, the error message is plain confusing and uninformative. 
I have replaced it with a clearer error message when the graph fails to build.
Now, for your test videos, it returns the following:
```
ValueError: Could not build calibration graph.
            Some group of cameras could not be paired by simultaneous calibration board detections.
            Check which cameras have different group numbers below to see the missing edges.
            {'Cam1': 0, 'Cam2': 3, 'Cam3': 3, 'Cam4': 3, 'Cam5': 3}
```
Here, Cam2, Cam3, Cam4, Cam5 are in one group, and Cam1 is in another group. 
Something might be wrong with the detections from Cam1 or perhaps it's in a weird location relative to other cameras and there are no simultaneous detections in your videos.

This error message will be present in aniposelib 0.4.2 .

Second, I dug deeper into why Cam1 has no detections for your video. Turns out that opencv does detect the Charuco board but somehow refuses to estimate a pose vector for the Charuco board, needed for initializing the extrinsics. 
In the future, I'd like to get away from these pose vectors and initialize the extrinsics directly based on commonly detected points.
But this is a todo for another time.

For your videos specifically, I recommend moving the Charuco board around a bit more (and rotating it too), so that there is less of a chance of running into this odd edge case.
